### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rodor03** [Epicnicity322/PlayMoreSounds#1]
java.lang.ArrayIndexOutOfBoundsException: -1
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.rehash(Int2IntOpenHashMap.java:1139)
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.removeEntry(Int2IntOpenHashMap.java:221)
	at it.unimi.dsi.fastutil.ints.Int2IntOpenHashMap.remove(Int2IntOpenHashMap.java:373)
	at com.destroystokyo.paper.util.maplist.EntityList.remove(EntityList.java:34)
	at net.minecraft.server.v1_15_R1.Chunk.a(Chunk.java:688)
	at net.minecraft.server.v1_15_R1.Chunk.b(Chunk.java:659)
	at net.minecraft.server.v1_15_R1.WorldServer.removeEntityFromChunk(WorldServer.java:1533)
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:538)
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327)
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
	at java.lang.Thread.run(Thread.java:748)

**Comment by chrisrnj** [comment]
This either isn't a PlayMoreSounds issue or you didn't report the full error.
