### ISSUE TITLE
Custom Discs addon error: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by h266579110** [Epicnicity322/PlayMoreSounds#15]
Paper 1.18.1-216

```
 - 2022/03/07 23:43:41.328
 - PlayMoreSounds v4.2

Addon Author(s): [Epicnicity322]
Path: D:\GameServer\Minecraft1181\plugins\PlayMoreSounds\Addons\Custom Discs.jar
Start addon exception:
java.lang.NoClassDefFoundError: com/epicnicity322/playmoresounds/bukkit/util/VersionUtils
	at com.epicnicity322.customdiscs.CustomDiscs.onStart(CustomDiscs.java:263)
	at PlayMoreSounds.jar//com.epicnicity322.playmoresounds.core.addons.AddonManager.callOnStart(AddonManager.java:181)
	at PlayMoreSounds.jar//com.epicnicity322.playmoresounds.core.addons.AddonManager.startAddons(AddonManager.java:160)
	at PlayMoreSounds.jar//com.epicnicity322.playmoresounds.bukkit.PlayMoreSounds.onEnable(PlayMoreSounds.java:278)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562)
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476)
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1211)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: Custom Discs is missing the class com.epicnicity322.playmoresounds.bukkit.util.VersionUtils (Probably from a not specified dependency). Please contact the author(s): [Epicnicity322]
	at PlayMoreSounds.jar//com.epicnicity322.playmoresounds.core.addons.AddonClassLoader.findClass(AddonClassLoader.java:119)
	at PlayMoreSounds.jar//com.epicnicity322.playmoresounds.core.addons.AddonClassLoader.findClass(AddonClassLoader.java:85)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 15 more

```

**Comment by chrisrnj** [comment]
This is a known addon issue and should be fixed soon
