### ISSUE TITLE
Problem with Nature Sound Replacer addon

### ISSUE THREAD

**Issue by TeQTabanca** [Epicnicity322/PlayMoreSounds#18]
- **After adding one of the default minecraft sounds to the .yml file of the addon Nature Sound Replacer and using the /pms reload command, it gives an error in the .log file.**

.log file
```
=====================================================================
>> Please report this file to [Epicnicity322]
>> https://github.com/Epicnicity322/PlayMoreSounds/
=====================================================================

 - 2023/05/19 20:30:36.496
 - PlayMoreSounds v4.1.2

PMS Reloading Error (Unknown):
java.lang.NoSuchMethodError: 'org.bukkit.NamespacedKey org.bukkit.Sound.getKey()'
	at com.epicnicity322.naturesoundreplacer.NatureSoundReplacerPacketAdapter.toBukkit(NatureSoundReplacerPacketAdapter.java:158)
	at com.epicnicity322.naturesoundreplacer.NatureSoundReplacerPacketAdapter.loadNatureSoundReplacer(NatureSoundReplacerPacketAdapter.java:121)
	at com.epicnicity322.naturesoundreplacer.NatureSoundReplacer.lambda$onStart$0(NatureSoundReplacer.java:21)
	at com.epicnicity322.playmoresounds.bukkit.PlayMoreSounds.reload(PlayMoreSounds.java:230)
	at com.epicnicity322.playmoresounds.bukkit.command.subcommand.ReloadSubCommand.run(ReloadSubCommand.java:71)
	at com.epicnicity322.epicpluginlib.bukkit.command.CommandHandler.onCommand(CommandHandler.java:69)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236)
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

- **Since the Nature Sound Replacer addon existed in the PlayMoreSounds plugin before version 4.1.2, I tried it in older versions, but it gives the same error. Any chance of an update? Because I need so much...**

**Minecraft Version: 1.12.2-Spigot**

**Comment by chrisrnj** [comment]
Unfortunately it's using a class that's available only on Spigot 1.14+, that's why you're getting this error
