### ISSUE TITLE
[NBS Song Player] PlayMoreSounds disabling itself

### ISSUE THREAD

**Issue by joex92** [Epicnicity322/PlayMoreSounds#4]
So I added the NPS addon, restarted, no errors, added a bunch of songs in the specified folder, restarted, I got this error:
```
23.06 19:13:57 [Server] INFO Enabling PlayMoreSounds v4.0.1
23.06 19:13:57 [Server] WARN WorldGuard Regions depends on the other addon(s): [Regions Handler]
23.06 19:13:57 [Server] INFO ============================================
23.06 19:13:57 [Server] INFO PlayMoreSounds has been enabled
23.06 19:13:57 [Server] INFO 1006 sounds available on 1.16.5
23.06 19:13:57 [Server] INFO ============================================
23.06 19:13:57 [Server] INFO PlayMoreSounds is using bStats as metrics collector.
23.06 19:13:57 [Server] INFO Checking for updates...
23.06 19:13:57 [Server] ERROR Error occurred while enabling PlayMoreSounds v4.0.1 (Is it up to date?)
23.06 19:13:57 [Server] INFO java.lang.NoSuchMethodError: 'java.nio.file.Path com.epicnicity322.playmoresounds.bukkit.PlayMoreSounds.getFolder()'
23.06 19:13:57 [Server] INFO at com.epicnicity322.nbssongplayer.NBSSongPlayer.<clinit>(NBSSongPlayer.java:33) ~[?:?]
23.06 19:13:57 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
23.06 19:13:57 [Server] INFO at java.lang.Class.forName(Class.java:398) ~[?:?]
23.06 19:13:57 [Server] INFO at com.epicnicity322.playmoresounds.core.addons.AddonClassLoader.<init>(AddonClassLoader.java:48) ~[?:?]
23.06 19:13:57 [Server] INFO at com.epicnicity322.playmoresounds.core.addons.AddonManager.lambda$registerAddons$4(AddonManager.java:132) ~[?:?]
23.06 19:13:57 [Server] INFO at java.util.TreeMap.forEach(TreeMap.java:1002) ~[?:?]
23.06 19:13:57 [Server] INFO at com.epicnicity322.playmoresounds.core.addons.AddonManager.registerAddons(AddonManager.java:128) ~[?:?]
23.06 19:13:57 [Server] INFO at com.epicnicity322.playmoresounds.bukkit.PlayMoreSounds.onEnable(PlayMoreSounds.java:252) ~[?:?]
23.06 19:13:58 [Multicraft] Skipped 19 lines due to rate limit (40/s)
```
Using [Airplane.GG](airplane.gg) 1.16.5, a paper fork...

**Comment by chrisrnj** [comment]
It looks like you have an older version of this addon, have you deleted your Addons folder before updating PlayMoreSounds? If not, do that and install again using the '/pms addons' command

**Comment by joex92** [comment]
oh... i didn't know the addons could be installed like that... I´ll try that... I downloaded it from the forum page...

**Comment by chrisrnj** [comment]
That's because I just released this feature yesterday. If you have any other issues please let me know!
